spring:
  profiles: cloud

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: https://weather-app-eureka-server.herokuapp.com/eureka/
  instance:
    secure-port: 443
    secure-port-enabled: true
    non-secure-port: 80


server:
  ssl:
    enabled: true