server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: https://weather-app-eureka-server.herokuapp.com/eureka
